# FROM node:18
# RUN mkdir -p /opt/node/js \
#     && cd /opt/node \
#     && npm i canvas

# WORKDIR /opt/node/js

# ENTRYPOINT ["node"]


FROM public.ecr.aws/lambda/nodejs:18

ENV LAMBDA_TASK_ROOT=/var/task
ENV LAMBDA_RUNTIME_DIR=/var/runtime

# Install packages necessary for canvas
RUN yum -y update
RUN yum -y install gcc-c++ cairo-devel pango-devel libjpeg-turbo-devel giflib-devel gcc44

# Assumes your function is named "app.js", and there is a package.json file in the app directory 
COPY index.js package.json ${LAMBDA_TASK_ROOT}/

# Install NPM dependencies for function
RUN npm install

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "index.handler" ]